
# The source code in this file is hereby placed in the public domain.
# 29 August 1996, Michael Wolfe, Oregon, USA

INCLUDE=-I. -I../src -I/usr/openwin/include -I/usr/dt/include
LIBRARY=-L/usr/openwin/lib -L/usr/dt/lib

CC=gcc $(INCLUDE)
LEX=flex

INSTALL=/home/1/mwolfe/bin/solaris
SRC=../src

include $(SRC)/dflo.mk
